name: Create docker images (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      allowed_frame_url:
        type: string
        description: Allowed Frame Url
        required: true

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db-type: [postgresql, mysql]

    steps:
      - uses: actions/checkout@v3

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to ghcr.io for ${{ matrix.db-type }}
        with:
          image: umami
          tags: ${{ matrix.db-type }}-${{ inputs.version }}, ${{ matrix.db-type }}-latest
          buildArgs: DATABASE_TYPE=${{ matrix.db-type }} ALLOWED_FRAME_URLS=${{ inputs.allowed_frame_url || "https://deploy.polothemes.com"}}
          registry: ghcr.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    #   - uses: mr-smithers-excellent/docker-build-push@v6
    #     name: Build & push Docker image to docker.io for ${{ matrix.db-type }}
    #     with:
    #       image: umamisoftware/umami
    #       tags: ${{ matrix.db-type }}-${{ inputs.version }}, ${{ matrix.db-type }}-latest
    #       buildArgs: DATABASE_TYPE=${{ matrix.db-type }}
    #       registry: docker.io
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
